// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteGame(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GetFileDir(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function InstallGame(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function LoadMetadata():Promise<any>;

export function LocateExecutive(arg1:string):Promise<string>;

export function LocateThumbnail(arg1:string,arg2:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenImageFile(arg1:string):Promise<string>;

export function RenameFolder(arg1:string,arg2:string,arg3:string):Promise<{[key: string]: string}>;

export function SaveMetadata(arg1:any):Promise<void>;

export function Start(arg1:string):Promise<void>;

export function TestGame(arg1:string,arg2:string):Promise<{[key: string]: any}>;
