// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileDir(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallGame():Promise<{[key: string]: string}>;

export function LoadMetadata():Promise<any>;

export function OpenImageFile():Promise<string>;

export function SaveMetadata(arg1:any):Promise<void>;
