// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileDir(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetFileDir'](arg1, arg2, arg3, arg4, arg5);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallGame() {
  return window['go']['main']['App']['InstallGame']();
}

export function LoadMetadata() {
  return window['go']['main']['App']['LoadMetadata']();
}

export function LocateExecutive() {
  return window['go']['main']['App']['LocateExecutive']();
}

export function LocateThumbnail() {
  return window['go']['main']['App']['LocateThumbnail']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenImageFile() {
  return window['go']['main']['App']['OpenImageFile']();
}

export function SaveMetadata(arg1) {
  return window['go']['main']['App']['SaveMetadata'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}
