// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteGame(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteGame'](arg1, arg2, arg3);
}

export function GetFileDir(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFileDir'](arg1, arg2, arg3, arg4);
}

export function InstallGame() {
  return window['go']['main']['App']['InstallGame']();
}

export function LoadMetadata() {
  return window['go']['main']['App']['LoadMetadata']();
}

export function LocateExecutive() {
  return window['go']['main']['App']['LocateExecutive']();
}

export function LocateThumbnail(arg1, arg2) {
  return window['go']['main']['App']['LocateThumbnail'](arg1, arg2);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenImageFile(arg1) {
  return window['go']['main']['App']['OpenImageFile'](arg1);
}

export function RenameFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2, arg3);
}

export function SaveMetadata(arg1) {
  return window['go']['main']['App']['SaveMetadata'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}
